// This is the Main class of this project
// Introduces the application
// By Siddharth Gupta
// July 26, 2017
package Intro;

/**
 *
 * @author siddharth
 */
public class Introduction extends javax.swing.JFrame {

    /**
     * Creates new form Introduction
     */
    public Introduction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleSG = new javax.swing.JLabel();
        btnExitSG = new javax.swing.JButton();
        lblProgInfoSG = new javax.swing.JLabel();
        btnPtsTEqnSG = new javax.swing.JButton();
        btnIntersectLineSG = new javax.swing.JButton();
        btnDivExpSG = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitleSG.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        lblTitleSG.setText("Introduction");

        btnExitSG.setText("Exit Appliction");
        btnExitSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitSGActionPerformed(evt);
            }
        });

        lblProgInfoSG.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblProgInfoSG.setText("Programs:");

        btnPtsTEqnSG.setText("Two Points to Linear Equation");
        btnPtsTEqnSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPtsTEqnSGActionPerformed(evt);
            }
        });

        btnIntersectLineSG.setText("Intersection of Lines");
        btnIntersectLineSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntersectLineSGActionPerformed(evt);
            }
        });

        btnDivExpSG.setText("Division Exponent Rules");
        btnDivExpSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivExpSGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExitSG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(lblTitleSG))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPtsTEqnSG)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btnIntersectLineSG)))))
                .addGap(162, 162, 162))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(lblProgInfoSG))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btnDivExpSG)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblTitleSG))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExitSG, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblProgInfoSG)
                .addGap(18, 18, 18)
                .addComponent(btnPtsTEqnSG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIntersectLineSG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDivExpSG)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitSGActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitSGActionPerformed

    private void btnPtsTEqnSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPtsTEqnSGActionPerformed
        new Two_Points_To_Equation.Info1().setVisible(true);
        // Opens "Info1" JFrame class for the program
        // Closes this JFrame class
    }//GEN-LAST:event_btnPtsTEqnSGActionPerformed

    private void btnIntersectLineSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntersectLineSGActionPerformed
        new Line_Intersect.Info1().setVisible(true);
        // Opens "Info1" JFrame class for the program
        this.dispose();
        // Closes this JFrame class
    }//GEN-LAST:event_btnIntersectLineSGActionPerformed

    private void btnDivExpSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivExpSGActionPerformed
        new Division_Exponent.Info1().setVisible(true);
        //Opens Info1 JFrame class
        this.dispose();
        //closes this JFram/window
    }//GEN-LAST:event_btnDivExpSGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Introduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Introduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Introduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Introduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Introduction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDivExpSG;
    private javax.swing.JButton btnExitSG;
    private javax.swing.JButton btnIntersectLineSG;
    private javax.swing.JButton btnPtsTEqnSG;
    private javax.swing.JLabel lblProgInfoSG;
    private javax.swing.JLabel lblTitleSG;
    // End of variables declaration//GEN-END:variables
}
