//Final Quiz--Siddharth Gupta-- July 26
package Two_Points_To_Equation;


public class FinalQuiz extends javax.swing.JFrame {

    /**
     * Creates new form FinalQuiz
     */
    
    
    
    public FinalQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleSG = new javax.swing.JLabel();
        btnBeginSG = new javax.swing.JButton();
        lblInfoSG = new javax.swing.JLabel();
        txtAnsSG = new javax.swing.JTextField();
        btnSubmitSG = new javax.swing.JButton();
        btnBackSG = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaOutQSG = new javax.swing.JTextArea();
        lblOutSolnSG = new javax.swing.JLabel();
        btnIntroSG = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitleSG.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        lblTitleSG.setText("Final Quiz (1 Hard Question)");

        btnBeginSG.setText("Begin");
        btnBeginSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeginSGActionPerformed(evt);
            }
        });

        lblInfoSG.setText("My Answer:");

        btnSubmitSG.setText("Submit");
        btnSubmitSG.setEnabled(false);
        btnSubmitSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitSGActionPerformed(evt);
            }
        });

        btnBackSG.setText("<-- Back");
        btnBackSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSGActionPerformed(evt);
            }
        });

        jtaOutQSG.setColumns(20);
        jtaOutQSG.setLineWrap(true);
        jtaOutQSG.setRows(5);
        jScrollPane1.setViewportView(jtaOutQSG);

        lblOutSolnSG.setFont(new java.awt.Font("L M Roman Slant10", 0, 24)); // NOI18N

        btnIntroSG.setText("Back to Intro");
        btnIntroSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroSGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(btnBeginSG))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblInfoSG)
                        .addGap(18, 18, 18)
                        .addComponent(txtAnsSG, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(btnSubmitSG))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblOutSolnSG, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBackSG)
                        .addGap(59, 59, 59)
                        .addComponent(lblTitleSG)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnIntroSG, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleSG)
                    .addComponent(btnBackSG))
                .addGap(18, 18, 18)
                .addComponent(btnBeginSG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoSG)
                    .addComponent(txtAnsSG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmitSG)
                .addGap(26, 26, 26)
                .addComponent(lblOutSolnSG, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIntroSG)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int x_1,y_1,x_2,y_2;//initialize vars
    private void btnBeginSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeginSGActionPerformed
        // TODO add your handling code here:
        x_1=(int)Math.floor(Math.random()*40-20);//Gens Randnum from -20 to 20
        y_1=(int)Math.floor(Math.random()*40-20);//Gens Randnum from -20 to 20
        this.btnBeginSG.setEnabled(false);//Disables this button
        do{
            x_2=(int)Math.floor(Math.random()*40-20);//Gens Randnum from -20 to 20
            y_2=(int)Math.floor(Math.random()*40-20);//Gens Randnum from -20 to 20
        }while(x_1==x_2||y_1==y_2);//Forces different numbers, so non-undefined cartesian solution
        this.btnSubmitSG.setEnabled(true);//Enables submit
        this.jtaOutQSG.setText("You are allowed a calculator. Give your answer to 2 decimal places (e.g. \"y=-1.31x-2.00\").\nQUESTION: What line crosses ("+x_1+","+y_1+"), and ("+x_2+","+y_2+")");//Output
    }//GEN-LAST:event_btnBeginSGActionPerformed

    private void btnBackSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSGActionPerformed
        new Practice_Qs().setVisible(true);
        //opens prev. JFrame
        this.dispose();
        //closes this JFrame class
    }//GEN-LAST:event_btnBackSGActionPerformed

    private void btnIntroSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroSGActionPerformed
        new Intro.Introduction().setVisible(true);
        //opens intro JFrame
        this.dispose();
        //closes this JFrame class
    }//GEN-LAST:event_btnIntroSGActionPerformed

    public String PtLnSoln(int x_1, int y_1, int x_2, int y_2){
        double Slope=((double)(y_1-y_2))/((double)(x_1-x_2));
        double Shift=((double)y_1)-Slope*x_1;
        //rounded vers:
        double rSlope=Math.round(Slope*100.0)/100.0;
        double rShift=Math.round(Shift*100.0)/100.0;
        //since nobody types +-, if solves syntax:
        if(rShift>=0){
            return ("y="+rSlope+"x"+"+"+rShift);//y=mx+b (b is positive0
        }
        else{
            return ("y="+rSlope+"x"+rShift);//y=mx-b (b is neg, automatically "-" included
        }
    }
    
    private void btnSubmitSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitSGActionPerformed
        //make soln:
        String strSolSG=PtLnSoln(x_1,y_1,x_2,y_2);
        String strSubSG=this.txtAnsSG.getText();
        if(strSubSG.equals(strSolSG)){
            //Correct,
            this.lblOutSolnSG.setText("CONGRATULATIONS! You are correct!");
        }
        else{
            //Wrong
            this.lblOutSolnSG.setText("Try Again- Practice makes Perfect!");
        }
    }//GEN-LAST:event_btnSubmitSGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackSG;
    private javax.swing.JButton btnBeginSG;
    private javax.swing.JButton btnIntroSG;
    private javax.swing.JButton btnSubmitSG;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaOutQSG;
    private javax.swing.JLabel lblInfoSG;
    private javax.swing.JLabel lblOutSolnSG;
    private javax.swing.JLabel lblTitleSG;
    private javax.swing.JTextField txtAnsSG;
    // End of variables declaration//GEN-END:variables
}
