//By Siddharth Gupta, on July 26th
//This is information for this package
package Two_Points_To_Equation;

/**
 *
 * @author siddharth
 */
public class Info1 extends javax.swing.JFrame {

    /**
     * Creates new form Info1
     */
    public Info1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaInfoSG = new javax.swing.JTextArea();
        lblTitleSG = new javax.swing.JLabel();
        btnBackSG = new javax.swing.JButton();
        btnNextSG = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtaInfoSG.setColumns(20);
        jtaInfoSG.setLineWrap(true);
        jtaInfoSG.setRows(5);
        jtaInfoSG.setText("To calculate the equation of a line crossing two points,\nfirst calculate the slope (which is represented by the \nletter m in the equation y=mx+b). m is the difference in \nthe y values divided by the difference in the x values. \nThis equation is usually called \"delta y over delta x\" or \n\"rise over run\". Now that you've solved for m, sub it into \n\"y=mx+b\" along with the values for one of the point to \nsolve for b. Now youre done! You have all the variables \nyou need: m,and b.");
        jScrollPane1.setViewportView(jtaInfoSG);

        lblTitleSG.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        lblTitleSG.setText("Information");

        btnBackSG.setText("<-- Back");
        btnBackSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSGActionPerformed(evt);
            }
        });

        btnNextSG.setText("Next -->");
        btnNextSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextSGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackSG)
                .addGap(14, 14, 14)
                .addComponent(lblTitleSG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNextSG)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleSG)
                    .addComponent(btnBackSG)
                    .addComponent(btnNextSG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSGActionPerformed
        new Intro.Introduction().setVisible(true);
        // Goes back to the intro JFrame
        this.dispose();
        // Closes this JFrame class
    }//GEN-LAST:event_btnBackSGActionPerformed

    private void btnNextSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextSGActionPerformed
        new Practice_Qs().setVisible(true);
        // Goes to the practice questions JFrame
        this.dispose();
        // Closes this JFrame class
    }//GEN-LAST:event_btnNextSGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackSG;
    private javax.swing.JButton btnNextSG;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaInfoSG;
    private javax.swing.JLabel lblTitleSG;
    // End of variables declaration//GEN-END:variables
}
