//Practice questions--Siddharth Gupta-- July 26
package Two_Points_To_Equation;
import java.util.*;
/**
 *
 * @author siddharth
 */
public class Practice_Qs extends javax.swing.JFrame {


    public Practice_Qs() {
        initComponents();
    }
    ArrayList <String> strQuestionsSG=new ArrayList();
    //Questions
    ArrayList <String> strAnswersSG=new ArrayList();
    //Answers to questions
    int intRandSG=(int)Math.floor(Math.random()*4);
    // random number to be used later
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleSG = new javax.swing.JLabel();
        btnBackSG = new javax.swing.JButton();
        btnNextSG = new javax.swing.JButton();
        btnGenQSG = new javax.swing.JButton();
        lblOutGenQSG = new javax.swing.JLabel();
        btnRevealSG = new javax.swing.JButton();
        lblOutRevealSG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitleSG.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        lblTitleSG.setText("Practice Questions");

        btnBackSG.setText("<-- Back");
        btnBackSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSGActionPerformed(evt);
            }
        });

        btnNextSG.setText("Next -->");
        btnNextSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextSGActionPerformed(evt);
            }
        });

        btnGenQSG.setText("Generate Question");
        btnGenQSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenQSGActionPerformed(evt);
            }
        });

        btnRevealSG.setText("Reveal Answer");
        btnRevealSG.setDoubleBuffered(true);
        btnRevealSG.setEnabled(false);
        btnRevealSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevealSGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackSG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitleSG)
                .addGap(18, 18, 18)
                .addComponent(btnNextSG)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOutRevealSG, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(btnGenQSG))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblOutGenQSG, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(205, 205, 205)
                            .addComponent(btnRevealSG))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNextSG)
                    .addComponent(btnBackSG)
                    .addComponent(lblTitleSG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenQSG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOutGenQSG, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRevealSG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOutRevealSG, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSGActionPerformed
        new Info1().setVisible(true);
        //Open Info JFrame class
        this.dispose();
        //Closes this
    }//GEN-LAST:event_btnBackSGActionPerformed

    private void btnGenQSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenQSGActionPerformed
        Collections.addAll(strQuestionsSG,"What is the equation of the line which crosses (6,2) and (7,7)?","What is the equation of the line which crosses (9,7) and (4,6)?","What is the equation of the line which crosses (1,10) and (2,4)?","What is the equation of the line which crosses (1,0) and (0,4)?");
        this.lblOutGenQSG.setText(strQuestionsSG.get(intRandSG));
        this.btnRevealSG.setEnabled(true);
        this.btnGenQSG.setEnabled(false);
        //Set question, disable self, enable reveal
    }//GEN-LAST:event_btnGenQSGActionPerformed

    private void btnRevealSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevealSGActionPerformed
        Collections.addAll(strAnswersSG,"y=5x-28","y=(x/5)+(26/5)","y=-6x+16","y=-4x+4");
        this.lblOutRevealSG.setText(strAnswersSG.get(intRandSG));
        //Set answer and enable regen
        int intOldRandSG=intRandSG;//Prev. Rand num
        while (intOldRandSG==intRandSG){ //Making sure new rand is different
            intRandSG=(int)Math.floor(Math.random()*4);
            //Redo rand for new Question
        }
        this.btnGenQSG.setEnabled(true);
        this.btnRevealSG.setEnabled(false);
        //disable itself again, enable QGen
    }//GEN-LAST:event_btnRevealSGActionPerformed

    private void btnNextSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextSGActionPerformed
        new FinalQuiz().setVisible(true);
        //Opens finalquiz
        this.dispose();
        //Closes this JFrame class
    }//GEN-LAST:event_btnNextSGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practice_Qs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practice_Qs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practice_Qs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practice_Qs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practice_Qs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackSG;
    private javax.swing.JButton btnGenQSG;
    private javax.swing.JButton btnNextSG;
    private javax.swing.JButton btnRevealSG;
    private javax.swing.JLabel lblOutGenQSG;
    private javax.swing.JLabel lblOutRevealSG;
    private javax.swing.JLabel lblTitleSG;
    // End of variables declaration//GEN-END:variables
}
